// src/auth/dto/responseAuthDto.dto.ts
import { ApiProperty } from '@nestjs/swagger';
import { Expose, Type } from 'class-transformer';
import { AuthenticatedUserDto } from './AuthenticatedUserDto.dto';

export class AuthResponseDto {
  @ApiProperty({
    example: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...',
    description: 'The JWT access token generated by the server',
  })
  @Expose()
  access_token: string;

  @ApiProperty({
    type: AuthenticatedUserDto,
    description: 'The authenticated user details',
  })
  @Expose()
  @Type(() => AuthenticatedUserDto)
  user: AuthenticatedUserDto;
}
